version: '3'

services:
  web:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - ${DOCKER_WEB_PORT}:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      #- ./docker/nginx/certs:/etc/nginx/certs
      - ./:/var/www/html
    links:
      - php

  php:
    restart: unless-stopped
    build:
      context: ./docker/php-fpm
      args:
        - DOCK_USER_ID=${DOCKER_USER_ID}
        - DOCK_GROUP_ID=${DOCKER_GROUP_ID}
    volumes:
      #- ./docker/php-fpm/config/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html
    environment:
      - DB_HOST=mysql
    links:
      - mysql

  mysql:
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
      PMA_ABSOLUTE_URI: ${APP_URL}/bps_pma/
    ports:
      - ${DOCKER_PHPMYADMIN_PORT}:80
